export interface Perfume {
  id: string;
  name: string;
  brand: string;
  price: number;
  ml?: number;
  originalPrice?: number;
  gender: "male" | "female" | "unisex";
  notes: string[];
  description: string;
  ageRange: {
    min: number;
    max: number;
  };
  characteristics: string[];
  shopierLink?: string;
}

export const perfumes: Perfume[] = [
  {
    id: "mfk-br540",
    name: "Baccarat Rouge 540",
    brand: "Blue Perfumery Exclusive",
    price: 1250,
    ml: 70,
    originalPrice: 500,
    gender: "unisex",
    notes: ["safran", "yasemin", "amber", "sedir"],
    description: "Blue Perfumery koleksiyonundan lüks ve sofistike bir koku. Tatlı ve odunsu notalar ile öne çıkar.",
    ageRange: { min: 20, max: 35 },
    characteristics: ["tatlı", "odunsu", "amber", "sıcak"],
    shopierLink: "https://www.shopier.com/blueperfumery/baccarat-rouge-540",
  },
  {
    id: "mfk-oud-satin",
    name: "Oud Satin Mood",
    brand: "Blue Perfumery Premium",
    price: 1350,
    ml: 70,
    originalPrice: 510,
    gender: "unisex",
    notes: ["ud", "gül", "vanilya", "benjamin"],
    description: "Blue Perfumery'nin zengin ve yoğun oryantal kokusu.",
    ageRange: { min: 20, max: 50 },
    characteristics: ["oryantal", "zengin", "tatlı", "odunsu"],
    shopierLink: "https://www.shopier.com/blueperfumery/oud-satin-mood",
  },
  {
    id: "mfk-grand-soir",
    name: "Grand Soir",
    brand: "Blue Perfumery Signature",
    price: 1200,
    ml: 70,
    originalPrice: 300,
    gender: "unisex",
    notes: ["amber", "vanilya", "benjamin", "tonka fasulyesi"],
    description: "Blue Perfumery'den sıcak ve baştan çıkarıcı amber kokusu.",
    ageRange: { min: 25, max: 50 },
    characteristics: ["amber", "sıcak", "tatlı", "vanilyalı"],
    shopierLink: "https://www.shopier.com/blueperfumery/grand-soir",
  },
  {
    id: "tf-oud-wood",
    name: "Oud Wood",
    brand: "Blue Perfumery Luxury",
    price: 1400,
    ml: 50,
    originalPrice: 480,
    gender: "male",
    notes: ["ud", "gül ağacı", "kakule", "sandal ağacı"],
    description: "Sofistike ve maskülen bir ağaç kokusu.",
    ageRange: { min: 25, max: 55 },
    characteristics: ["odunsu", "baharatlı", "lüks", "rafine"],
    shopierLink: "https://www.shopier.com/blueperfumery/oud-wood",
  },
  {
    id: "tf-lost-cherry",
    name: "Lost Cherry",
    brand: "Blue Perfumery Premium",
    price: 20000,
    ml: 100,
    originalPrice: 700,
    gender: "female",
    notes: ["kiraz", "badem", "tonka fasulyesi", "peru balsamı"],
    description: "Tatlı ve baştan çıkarıcı kiraz kokusu.",
    ageRange: { min: 20, max: 45 },
    characteristics: ["tatlı", "meyveli", "gurme"],
    shopierLink: "https://www.shopier.com/blueperfumery/lost-cherry",
  },
  {
    id: "tf-tobacco-vanille",
    name: "Tobacco Vanille",
    brand: "Blue Perfumery Premium",
    price: 1300,
    ml: 50,
    originalPrice: 310,
    gender: "unisex",
    notes: ["tütün", "vanilya", "kakao", "tonka fasulyesi"],
    description: "Sıcak ve zengin tütün-vanilya kokusu.",
    ageRange: { min: 25, max: 50 },
    characteristics: ["tatlı", "baharatlı", "sıcak", "tütünlü"],
    shopierLink: "https://www.shopier.com/blueperfumery/tobacco-vanille",
  },
  {
    id: "tf-bitter-peach",
    name: "Bitter Peach",
    brand: "Blue Perfumery Premium",
    price: 1300,
    ml: 50,
    originalPrice: 460,
    gender: "female",
    notes: ["şeftali", "kakule", "rom", "vanilya"],
    description: "Tatlı-acı şeftali aroması.",
    ageRange: { min: 18, max: 40 },
    characteristics: ["meyveli", "tatlı", "baharatlı"],
    shopierLink: "https://www.shopier.com/blueperfumery/bitter-peach",
  },
  {
    id: "tf-ebene-fume",
    name: "Ébène Fumé",
    brand: "Blue Perfumery Exclusive",
    price: 1350,
    ml: 50,
    originalPrice: 480,
    gender: "unisex",
    notes: ["kutsal odun", "deri", "kara biber", "abanoz"],
    description: "Mistik ve derin bir ahşap kokusu.",
    ageRange: { min: 27, max: 60 },
    characteristics: ["odunsu", "dumanlı", "gizemli", "derin"],
    shopierLink: "https://www.shopier.com/blueperfumery/ebene-fume",
  },
  {
    id: "tf-ombre-leather",
    name: "Ombre Leather",
    brand: "Blue Perfumery Premium",
    price: 1250,
    ml: 50,
    originalPrice: 230,
    gender: "unisex",
    notes: ["deri", "kakule", "yasemin", "yosun"],
    description: "Yumuşak ve sofistike bir deri kokusu.",
    ageRange: { min: 23, max: 55 },
    characteristics: ["deri", "baharatlı", "floral", "toprak"],
    shopierLink: "https://www.shopier.com/blueperfumery/ombre-leather",
  },
  {
    id: "creed-original-santal",
    name: "Original Santal",
    brand: "Blue Perfumery Luxury",
    price: 1450,
    ml: 100,
    originalPrice: 470,
    gender: "male",
    notes: ["sandal ağacı", "tarçın", "kişniş", "lavanta"],
    description: "Lüks ve egzotik bir sandal ağacı kokusu.",
    ageRange: { min: 28, max: 55 },
    characteristics: ["odunsu", "baharatlı", "sıcak", "aromatik"],
    shopierLink: "https://www.shopier.com/blueperfumery/original-santal",
  },
  {
    id: "xerjoff-naxos",
    name: "Naxos",
    brand: "Blue Perfumery Exclusive",
    price: 1500,
    ml: 100,
    originalPrice: 275,
    gender: "male",
    notes: ["tütün", "ballı", "vanilya", "tonka fasulyesi"],
    description: "Zengin ve sofistike bir tütün kokusu.",
    ageRange: { min: 25, max: 50 },
    characteristics: ["tütünlü", "tatlı", "ballı", "vanilyalı"],
    shopierLink: "https://www.shopier.com/blueperfumery/naxos",
  },
  {
    id: "xerjoff-alexandria",
    name: "Alexandria II",
    brand: "Blue Perfumery Exclusive",
    price: 1600,
    ml: 100,
    originalPrice: 800,
    gender: "unisex",
    notes: ["ud", "vanilya", "amber", "sedir"],
    description: "Lüks ve oryantal bir koku.",
    ageRange: { min: 25, max: 45 },
    characteristics: ["oryantal", "odunsu", "zengin"],
    shopierLink: "https://www.shopier.com/blueperfumery/alexandria-ii",
  },
  {
    id: "ch-212-men",
    name: "212 Men",
    brand: "Blue Perfumery Urban",
    price: 650,
    ml: 100,
    originalPrice: 100,
    gender: "male",
    notes: ["yeşil baharatlar", "greyfurt", "sandal ağacı", "günlük"],
    description: "Modern ve dinamik bir erkek kokusu",
    ageRange: { min: 18, max: 35 },
    characteristics: ["ferah", "baharatlı", "odunsu", "şehirli"],
    shopierLink: "https://www.shopier.com/blueperfumery/212-men",
  },
  {
    id: "invictus",
    name: "Invictus",
    brand: "Blue Perfumery Urban",
    price: 600,
    ml: 50,
    originalPrice: 100,
    gender: "male",
    notes: ["greyfurt", "deniz", "guaiac ağacı"],
    description: "Taze ve maskülen bir koku",
    ageRange: { min: 20, max: 35 },
    characteristics: ["ferah", "deniz", "odunsu"],
    shopierLink: "https://www.shopier.com/blueperfumery/invictus",
  },
  {
    id: "chanel-chance",
    name: "Chance",
    brand: "Blue Perfumery Classic",
    price: 900,
    ml: 50,
    originalPrice: 200,
    gender: "female",
    notes: ["pembe biber", "yasemin", "paçuli"],
    description: "Zarif ve feminen bir koku.",
    ageRange: { min: 19, max: 45 },
    characteristics: ["çiçeksi", "ferah", "baharatlı"],
    shopierLink: "https://www.shopier.com/blueperfumery/chance",
  },
  {
    id: "chanel-coco-mademoiselle",
    name: "Coco Mademoiselle",
    brand: "Blue Perfumery Classic",
    price: 980,
    ml: 50,
    originalPrice: 140,
    gender: "female",
    notes: ["portakal", "yasemin", "gül", "paçuli"],
    description: "Modern ve çekici bir klasik kadın kokusu.",
    ageRange: { min: 25, max: 50 },
    characteristics: ["çiçeksi", "ferah", "oryantal", "zarif"],
    shopierLink: "https://www.shopier.com/blueperfumery/coco-mademoiselle",
  },
  {
    id: "armani-stronger-with-you",
    name: "Stronger With You",
    brand: "Blue Perfumery Urban",
    price: 750,
    ml: 50,
    originalPrice: 130,
    gender: "male",
    notes: ["adaçayı", "frezya", "cıvıltı", "vanilya"],
    description: "Güçlü ve çekici bir erkek kokusu",
    ageRange: { min: 20, max: 40 },
    characteristics: ["baharatlı", "tatlı", "aromatik", "sıcak"],
    shopierLink: "https://www.shopier.com/blueperfumery/stronger-with-you",
  },
  {
    id: "armani-si",
    name: "Si",
    brand: "Blue Perfumery Classic",
    price: 820,
    ml: 100,
    originalPrice: 200,
    gender: "female",
    notes: ["siyahşeftali", "frezya", "vanilya", "ambroxan"],
    description: "Modern ve sofistike bir kadın kokusu.",
    ageRange: { min: 25, max: 50 },
    characteristics: ["fruity", "çiçeksi", "tatlı", "zarif"],
    shopierLink: "https://www.shopier.com/blueperfumery/si",
  },
  {
    id: "ex-nihilo-fleur-narcotique",
    name: "Fleur Narcotique",
    brand: "Blue Perfumery Exclusive",
    price: 1250,
    ml: 100,
    originalPrice: 325,
    gender: "unisex",
    notes: ["bergamot", "şeftali", "yasemin", "misk"],
    description: "Çiçeksi ve bağımlılık yaratan bir parfüm.",
    ageRange: { min: 22, max: 45 },
    characteristics: ["çiçeksi", "meyveli", "bağımlılık yapıcı", "sofistike"],
    shopierLink: "https://www.shopier.com/blueperfumery/fleur-narcotique",
  },
  {
    id: "nasomatto-black-afgano",
    name: "Black Afgano",
    brand: "Blue Perfumery Artisanal",
    price: 1180,
    ml: 30,
    originalPrice: 155,
    gender: "unisex",
    notes: ["kenevir", "kahve", "ud", "tütün"],
    description: "Derin ve karanlık bir bağımlılık parfümü.",
    ageRange: { min: 28, max: 55 },
    characteristics: ["reçineli", "karanlık", "yoğun", "bağımlılık yapıcı"],
    shopierLink: "https://www.shopier.com/blueperfumery/black-afgano",
  },
  {
    id: "guerlain-shalimar",
    name: "Shalimar",
    brand: "Blue Perfumery Classic",
    price: 890,
    ml: 90,
    originalPrice: 280,
    gender: "female",
    notes: ["bergamot", "iris", "vanilya", "günlük"],
    description: "Oryantal parfümeride bir başyapıt.",
    ageRange: { min: 30, max: 60 },
    characteristics: ["oryantal", "pudralı", "ikonik", "zamansız"],
    shopierLink: "https://www.shopier.com/blueperfumery/shalimar",
  },
  {
    id: "ysl-libre-woman",
    name: "Libre Woman",
    brand: "Blue Perfumery Classic",
    price: 800,
    ml: 50,
    originalPrice: 140,
    gender: "female",
    notes: ["lavanta", "portakal çiçeği", "vanilya", "misk"],
    description: "Modern ve özgür bir kadın kokusu.",
    ageRange: { min: 20, max: 40 },
    characteristics: ["çiçeksi", "warm", "ferah"],
    shopierLink: "https://www.shopier.com/blueperfumery/libre-woman",
  },
  {
    id: "dior-jadore",
    name: "J'Adore",
    brand: "Blue Perfumery Classic",
    price: 920,
    ml: 100,
    originalPrice: 300,
    gender: "female",
    notes: ["bergamot", "yasemin", "gül", "ylang-ylang"],
    description: "Zarif ve lüks bir çiçek buketi.",
    ageRange: { min: 25, max: 55 },
    characteristics: ["çiçeksi", "zarif", "feminen", "lüks"],
    shopierLink: "https://www.shopier.com/blueperfumery/jadore",
  },
  {
    id: "pdm-pegasus",
    name: "Pegasus",
    brand: "Blue Perfumery Luxury",
    price: 1250,
    ml: 125,
    originalPrice: 320,
    gender: "male",
    notes: ["badem", "vanilya", "sandal ağacı", "amber"],
    description: "Tatlı ve maskülen bir odunsu koku.",
    ageRange: { min: 25, max: 50 },
    characteristics: ["oryantal", "tatlı", "kremsi", "seçkin"],
    shopierLink: "https://www.shopier.com/blueperfumery/pegasus",
  },
  {
    id: "amouage-reflection-man",
    name: "Reflection Man",
    brand: "Blue Perfumery Luxury",
    price: 1380,
    ml: 100,
    originalPrice: 360,
    gender: "male",
    notes: ["rosemary", "yasemin", "neroli", "sandal ağacı"],
    description: "Zarif ve sofistike bir erkek parfümü.",
    ageRange: { min: 28, max: 60 },
    characteristics: ["çiçeksi", "ferah", "odunsu", "rafine"],
    shopierLink: "https://www.shopier.com/blueperfumery/reflection-man",
  },
  {
    id: "mfk-aqua-celestia",
    name: "Aqua Celestia",
    brand: "Blue Perfumery Premium",
    price: 1100,
    ml: 70,
    originalPrice: 360,
    gender: "unisex",
    notes: ["misket limonu", "nane", "frenk üzümü", "mimoza"],
    description: "Taze ve ferahlatıcı bir yaz kokusu.",
    ageRange: { min: 20, max: 45 },
    characteristics: ["ferah", "aquatik", "narenciyeli", "canlandırıcı"],
    shopierLink: "https://www.shopier.com/blueperfumery/aqua-celestia",
  },
  {
    id: "lveb",
    name: "La Vie Est Belle",
    brand: "Blue Perfumery Classic",
    price: 850,
    ml: 100,
    originalPrice: 220,
    gender: "female",
    notes: ["süsen", "paçuli", "pralin", "vanilya"],
    description: "Tatlı ve feminen bir koku.",
    ageRange: { min: 20, max: 45 },
    characteristics: ["tatlı", "gurme", "çiçeksi"],
    shopierLink: "https://www.shopier.com/blueperfumery/la-vie-est-belle",
  },
  {
    id: "terenzi-telea",
    name: "Telea",
    brand: "Blue Perfumery Exclusive",
    price: 1200,
    ml: 100,
    originalPrice: 730,
    gender: "unisex",
    notes: ["beyaz çiçekler", "vanilya", "misk", "amber"],
    description: "Zarif ve yoğun beyaz çiçek kokusu",
    ageRange: { min: 22, max: 45 },
    characteristics: ["çiçeksi", "tatlı", "warm", "yoğun"],
    shopierLink: "https://www.shopier.com/blueperfumery/telea",
  },
  {
    id: "terenzi-kirke",
    name: "Kirke",
    brand: "Blue Perfumery Exclusive",
    price: 1180,
    ml: 100,
    originalPrice: 320,
    gender: "female",
    notes: ["çarkıfelek", "şeftali", "vanilya", "misk"],
    description: "Çekici ve meyve dolu bir parfüm",
    ageRange: { min: 20, max: 40 },
    characteristics: ["meyveli", "tatlı", "tropikal", "zarif"],
    shopierLink: "https://www.shopier.com/blueperfumery/kirke",
  },
  {
    id: "memo-lalibela",
    name: "Lalibela",
    brand: "Blue Perfumery Artisanal",
    price: 1100,
    ml: 75,
    originalPrice: 300,
    gender: "unisex",
    notes: ["akgünlük", "vanilya", "misk", "badem"],
    description: "Ruhani ve derin bir koku deneyimi",
    ageRange: { min: 28, max: 55 },
    characteristics: ["günlük", "ruhani", "tatlı", "reçineli"],
    shopierLink: "https://www.shopier.com/blueperfumery/lalibela",
  },
  {
    id: "memo-italian-leather",
    name: "Italian Leather",
    brand: "Blue Perfumery Artisanal",
    price: 1150,
    ml: 75,
    originalPrice: 295,
    gender: "unisex",
    notes: ["deri", "tomato leaf", "vanilya", "tolu balsamı"],
    description: "İtalyan deri geleneğini yansıtan zarif bir koku",
    ageRange: { min: 25, max: 60 },
    characteristics: ["deri", "yeşil", "aromatik", "sofistike"],
    shopierLink: "https://www.shopier.com/blueperfumery/italian-leather",
  },
  {
    id: "memo-african-leather",
    name: "African Leather",
    brand: "Blue Perfumery Artisanal",
    price: 1200,
    ml: 75,
    originalPrice: 295,
    gender: "unisex",
    notes: ["deri", "kakule", "safran", "paçuli"],
    description: "Egzotik ve derili bir koku",
    ageRange: { min: 23, max: 50 },
    characteristics: ["deri", "baharatlı", "odunsu"],
    shopierLink: "https://www.shopier.com/blueperfumery/african-leather",
  },
  {
    id: "memo-marfa",
    name: "Marfa",
    brand: "Blue Perfumery Artisanal",
    price: 1150,
    ml: 75,
    originalPrice: 330,
    gender: "unisex",
    notes: ["portakal çiçeği", "sümbülteber", "beyaz misk", "sandal ağacı"],
    description: "Çölün ruhunu yansıtan büyüleyici bir koku",
    ageRange: { min: 25, max: 50 },
    characteristics: ["çiçeksi", "odunsu", "kremsi", "sanatsal"],
    shopierLink: "https://www.shopier.com/blueperfumery/marfa",
  },
  {
    id: "memo-ocean-leather",
    name: "Ocean Leather",
    brand: "Blue Perfumery Artisanal",
    price: 1180,
    ml: 75,
    originalPrice: 310,
    gender: "unisex",
    notes: ["deri", "deniz notaları", "sedir ağacı", "adaçayı"],
    description: "Okyanus esintileri ile buluşan deri notaları",
    ageRange: { min: 22, max: 45 },
    characteristics: ["deniz", "deri", "ferah", "derin"],
    shopierLink: "https://www.shopier.com/blueperfumery/ocean-leather",
  },
  {
    id: "memo-flam",
    name: "Flam",
    brand: "Blue Perfumery Artisanal",
    price: 1100,
    ml: 75,
    originalPrice: 290,
    gender: "unisex",
    notes: ["safran", "menekşe", "böğürtlen", "ud"],
    description: "İskandinav ormanlarının mistik atmosferi",
    ageRange: { min: 28, max: 55 },
    characteristics: ["meyveli", "odunsu", "gizemli", "zarif"],
    shopierLink: "https://www.shopier.com/blueperfumery/flam",
  },
  {
    id: "mancera-hindu-kush",
    name: "Hindu Kush",
    brand: "Blue Perfumery Premium",
    price: 920,
    ml: 120,
    originalPrice: 200,
    gender: "unisex",
    notes: ["kenevir", "günlük", "vetiver", "ud"],
    description: "Mistik dağların esrarengiz kokusu",
    ageRange: { min: 25, max: 50 },
    characteristics: ["odunsu", "dumanlı", "reçineli", "ayırt edici"],
    shopierLink: "https://www.shopier.com/blueperfumery/hindu-kush",
  },
  {
    id: "mancera-roses-vanille",
    name: "Roses Vanille",
    brand: "Blue Perfumery Premium",
    price: 880,
    ml: 120,
    originalPrice: 192,
    gender: "female",
    notes: ["gül", "vanilya", "şeker", "sedir"],
    description: "Tatlı ve romantik gül-vanilya kompozisyonu",
    ageRange: { min: 20, max: 40 },
    characteristics: ["çiçeksi", "tatlı", "gurme", "romantik"],
    shopierLink: "https://www.shopier.com/blueperfumery/roses-vanille",
  },
  {
    id: "mancera-cedrat-boise",
    name: "Cedrat Boise",
    brand: "Blue Perfumery Premium",
    price: 900,
    ml: 120,
    originalPrice: 195,
    gender: "unisex",
    notes: ["narenciye", "sedir", "deri", "vanilya"],
    description: "Energetic ve çarpıcı bir odunsu citrus kokusu",
    ageRange: { min: 22, max: 45 },
    characteristics: ["ferah", "odunsu", "narenciyeli", "modern"],
    shopierLink: "https://www.shopier.com/blueperfumery/cedrat-boise",
  },
  {
    id: "montale-chocolate-greedy",
    name: "Chocolate Greedy",
    brand: "Blue Perfumery Premium",
    price: 850,
    ml: 100,
    originalPrice: 190,
    gender: "unisex",
    notes: ["çikolata", "vanilya", "kahve", "kuru meyveler"],
    description: "Zengin ve tatlı çikolata kokusu",
    ageRange: { min: 20, max: 45 },
    characteristics: ["gurme", "tatlı", "zengin", "sıcak"],
    shopierLink: "https://www.shopier.com/blueperfumery/chocolate-greedy",
  },
  {
    id: "guerlain-homme-ideal-intense",
    name: "L'Homme Ideal Intense",
    brand: "Blue Perfumery Classic",
    price: 820,
    ml: 50,
    originalPrice: 125,
    gender: "male",
    notes: ["badem", "deri", "sedir", "tonka fasulyesi"],
    description: "Yoğun ve çekici bir maskülen parfüm",
    ageRange: { min: 25, max: 50 },
    characteristics: ["odunsu", "aromatik", "zarif", "yoğun"],
    shopierLink: "https://www.shopier.com/blueperfumery/lhomme-ideal-intense",
  },
  {
    id: "mar-barrois-ganymede",
    name: "Ganymede",
    brand: "Blue Perfumery Artisanal",
    price: 980,
    ml: 50,
    originalPrice: 300,
    gender: "unisex",
    notes: ["mandalina", "menekşe", "ölümsüz çiçek", "süet"],
    description: "Modern ve minimalist bir tasarım harikası",
    ageRange: { min: 25, max: 55 },
    characteristics: ["mineral", "süet", "ferah", "yenilikçi"],
    shopierLink: "https://www.shopier.com/blueperfumery/ganymede",
  },
  {
    id: "ysl-libre-parfum",
    name: "Libre Le Parfum",
    brand: "Blue Perfumery Classic",
    price: 850,
    ml: 50,
    originalPrice: 140,
    gender: "female",
    notes: ["lavanta", "portakal çiçeği", "vanilya", "zencefil"],
    description: "Orijinal Libre'nin daha yoğun ve sıcak versiyonu",
    ageRange: { min: 22, max: 45 },
    characteristics: ["çiçeksi", "warm", "zengin", "yoğun"],
    shopierLink: "https://www.shopier.com/blueperfumery/libre-le-parfum",
  },
  {
    id: "ysl-homme",
    name: "L'Homme",
    brand: "Blue Perfumery Classic",
    price: 780,
    ml: 100,
    originalPrice: 180,
    gender: "male",
    notes: ["zencefil", "bergamot", "cedarwood", "vetiver"],
    description: "Çekici ve zarif bir erkek kokusu",
    ageRange: { min: 22, max: 50 },
    characteristics: ["ferah", "baharatlı", "odunsu", "çok yönlü"],
    shopierLink: "https://www.shopier.com/blueperfumery/lhomme",
  },
  {
    id: "vs-bombshell",
    name: "Bombshell",
    brand: "Blue Perfumery Urban",
    price: 600,
    ml: 100,
    originalPrice: 190,
    gender: "female",
    notes: ["çarkıfelek", "şakayık", "vanilya", "misk"],
    description: "Genç ve çekici bir kadın kokusu",
    ageRange: { min: 18, max: 35 },
    characteristics: ["meyveli", "çiçeksi", "ferah", "feminen"],
    shopierLink: "https://www.shopier.com/blueperfumery/bombshell",
  },
  {
    id: "v-r-spicebomb-extreme",
    name: "Spicebomb Extreme",
    brand: "Blue Perfumery Premium",
    price: 880,
    ml: 50,
    originalPrice: 120,
    gender: "male",
    notes: ["tütün", "kara biber", "vanilya", "lavanta"],
    description: "Sıcak ve baharatlı bir erkek bombası",
    ageRange: { min: 22, max: 45 },
    characteristics: ["baharatlı", "tatlı", "sıcak", "yoğun"],
    shopierLink: "https://www.shopier.com/blueperfumery/spicebomb-extreme",
  },
  {
    id: "nishane-hacivat",
    name: "Hacivat",
    brand: "Blue Perfumery Artisanal",
    price: 980,
    ml: 50,
    originalPrice: 280,
    gender: "unisex",
    notes: ["bergamot", "pembe biber", "sedir", "paçuli"],
    description: "Taze ve sofistike bir narenciye-odunsu koku",
    ageRange: { min: 25, max: 50 },
    characteristics: ["ferah", "odunsu", "narenciyeli", "rafine"],
    shopierLink: "https://www.shopier.com/blueperfumery/hacivat",
  },
  {
    id: "ysl-black-opium",
    name: "Black Opium",
    brand: "Blue Perfumery Classic",
    price: 850,
    ml: 90,
    originalPrice: 220,
    gender: "female",
    notes: ["kahve", "vanilya", "beyaz çiçekler", "paçuli"],
    description: "Bağımlılık yaratan tatlı ve karanlık bir koku",
    ageRange: { min: 20, max: 45 },
    characteristics: ["tatlı", "kahveli", "çiçeksi", "bağımlılık yapıcı"],
    shopierLink: "https://www.shopier.com/blueperfumery/black-opium",
  },
];

// Helper function to get perfumes by gender/category
export function getPerfumesByGender(gender: string): Perfume[] {
  if (gender === "niche") {
    // Niche perfumes are typically from exclusive/artisanal brands
    return perfumes.filter(p => 
      p.brand.includes("Exclusive") || 
      p.brand.includes("Artisanal") || 
      p.brand.includes("Premium")
    );
  }
  
  if (gender === "men" || gender === "male") {
    return perfumes.filter(p => p.gender === "male" || p.gender === "unisex");
  }
  
  if (gender === "women" || gender === "female") {
    return perfumes.filter(p => p.gender === "female" || p.gender === "unisex");
  }
  
  return perfumes;
}

// Helper function to search perfumes by name
export function searchPerfumesByName(query: string): Perfume[] {
  const lowercaseQuery = query.toLowerCase();
  return perfumes.filter(p => 
    p.name.toLowerCase().includes(lowercaseQuery) ||
    p.brand.toLowerCase().includes(lowercaseQuery)
  );
}

// Helper function to get perfume by ID
export function getPerfumeById(id: string): Perfume | undefined {
  return perfumes.find(p => p.id === id);
}